[package]
name = "emoji-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Just a dummy emoji cli to play with Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
