name: ci-cargo

# Doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    tags:
      - "*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-cargo:
    name: Test, build and publish on crates.io
    runs-on: ubuntu-latest
    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # Doc: https://github.com/marketplace/actions/rustup-toolchain-install
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      # Doc: https://doc.rust-lang.org/cargo/commands/cargo-test.html
      - run: cargo test --all-features
      
      # Doc: https://doc.rust-lang.org/cargo/commands/cargo-build.html
      - run: cargo build --all-features --release

      # Doc: https://doc.rust-lang.org/cargo/commands/cargo-publish.html
      - run: cargo publish --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
